//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reccit.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Place> Places { get; set; }
        public DbSet<ReccitUser> ReccitUsers { get; set; }
        public DbSet<sqlblk_Place> sqlblk_Place { get; set; }
        public DbSet<sqlblk_ReccitUser> sqlblk_ReccitUser { get; set; }
        public DbSet<sqlblk_UserCheckin> sqlblk_UserCheckin { get; set; }
        public DbSet<sqlblk_UserFriendMap> sqlblk_UserFriendMap { get; set; }
        public DbSet<UserCheckin> UserCheckins { get; set; }
        public DbSet<UserFriendMap> UserFriendMaps { get; set; }
    }
}
