//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reccit.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReccitUser
    {
        public int ReccitUserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public long FacebookID { get; set; }
        public string TwitterHandler { get; set; }
        public string FourSquareID { get; set; }
    }
}
