//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reccit.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlblk_Place
    {
        public System.Guid sqlblkJobID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Zipcode { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public Nullable<bool> OpenTanle { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Price { get; set; }
        public string FacebookID { get; set; }
        public string FactualID { get; set; }
        public string FourSquareID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
    }
}
