//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reccit.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriendMap
    {
        public long UserID { get; set; }
        public long FriendID { get; set; }
    }
}
